// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CoinGecko_Phase2.API.Models;

public partial class StudentDbContext : DbContext
{
    public StudentDbContext(DbContextOptions<StudentDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<students> students { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<students>(entity =>
        {
            entity.HasKey(e => e.StudentId);

            entity.HasIndex(e => e.UserName, "IX_students_UserName").IsUnique();

            entity.Property(e => e.Email).IsRequired();
            entity.Property(e => e.Family).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.PassWord).IsRequired();
            entity.Property(e => e.PhoneNumber).IsRequired();
            entity.Property(e => e.UserName).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}