// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoinGecko_Phase2.API.Models;

public partial class students
{
    public int StudentId { get; set; }

    public string Name { get; set; }

    public string Family { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string UserName { get; set; }

    public string PassWord { get; set; }
}